services:
  postgres:
    image: postgres:17
    container_name: postgres-db-billy
    restart: always
    environment:
      POSTGRES_DB: billy_db
      POSTGRES_USER: billy
      POSTGRES_PASSWORD: billy
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
