"""add amount_owed and paid to participants

Revision ID: 7c10075728c3
Revises: 4dc94e77d9eb
Create Date: 2026-09-18 09:52:49.278691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c10075728c3'
down_revision: Union[str, Sequence[str], None] = '4dc94e77d9eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('amount_owed', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('participants', sa.Column('paid', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participants', 'paid')
    op.drop_column('participants', 'amount_owed')
    # ### end Alembic commands ###
